blank_issues_enabled: true
contact_links:
  - name: Diplodoc documentation (EN)
    url: https://diplodoc.com/docs/en/
  - name: Документация Диплодока
    url: https://diplodoc.com/docs/ru/
  - name: Diplodoc Community Chat (RU)
    url: Тelegram
