blank_issues_enabled: true
contact_links:
  - name: Diplodoc documentation (EN)
    url: https://diplodoc.com/docs/en/
    about: 1
  - name: Документация Диплодока (RU)
    url: https://diplodoc.com/docs/ru/
    about: 2
  - name: Комьюнити чат (RU)
    url: https://t.me/diplodoc_ru
    about: 3
