blank_issues_enabled: true
contact_links:
  - name: Diplodoc documentation (EN)
    url: https://diplodoc.com/docs/en/
    about: Try to find a solution to your problem in the documentation
  - name: Документация Диплодока (RU)
    url: https://diplodoc.com/docs/ru/
    about: Попробуйте найти решение своей проблемы в документации
  - name: Комьюнити чат (RU)
    url: https://t.me/diplodoc_ru
    about: Спросить у сообщества
